In [10]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_iris

In [15]:
iris = load_iris()
X = iris.data
y = iris.target

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
gnb = GaussianNB()

In [18]:
gnb.fit(X_train, y_train)

GaussianNB()

In [19]:
y_pred = gnb.predict(X_test)

In [20]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

In [21]:
print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 1.0
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



Explanation

    Load Dataset: The Iris dataset is loaded from scikit-learn's datasets module. It is a classic dataset used for classification.

    Split the Data: The dataset is split into training and testing sets using train_test_split.

    Initialize Model: The GaussianNB model from sklearn.naive_bayes is initialized.

    Train the Model: The model is trained using the training data (X_train and y_train).

    Make Predictions: Predictions are made on the test data (X_test).

    Evaluate the Model: The accuracy, confusion matrix, and classification report are used to evaluate the model's performance. These metrics provide insight into how well the model is performing on the test data.

Output

The output will show the accuracy of the model, the confusion matrix, and the classification report, which includes precision, recall, and F1-score for each class. This evaluation helps in understanding the effectiveness of the Naive Bayes classifier on the given dataset.